### ISSUE TITLE
window alignment is not relative to taskbar&screen

### ISSUE THREAD

**Issue by kanor** [yurenju/wallbox#20]
I prefer my taskbar in the bottom right corner just like in windows, next to gnome-do dock, and wallbox window always opens down, so I see it only in the lower workspace (i have 2x2 workspace), and a part of it even hangs out of the edge of the screen.

**Comment by yurenju** [comment]
fix in SHA: b29334e8734a49eeaf7cef297c230a910c885c91
will integrate on wallbox v0.4
